run:
  go: "1.22"
  tests: true

# See: https://golangci-lint.run/usage/linters/
linters-settings:
  depguard:
    rules:
      main:
        # List of allowed packages.
        allow:
          - $gostd
          - app/api
          - app/models
          - app/redis
          - app/bellhop
          - app/db
          - app/service
          - github.com/joho/godotenv
          - github.com/redis/go-redis/v9
          - gitlab.online-fx.com/go-packages/apirequest
          - gitlab.online-fx.com/go-packages/apiresponse
          - gitlab.online-fx.com/go-packages/envchecker
          - gitlab.online-fx.com/go-packages/gormdb
          - gitlab.online-fx.com/go-packages/logger
          - gitlab.online-fx.com/go-packages/prometheus
          - gorm.io/driver/postgres
          - gorm.io/gorm

  funlen:
    lines: 150
    statements: 80

  gci:
    skip-generated: false
    custom-order: true
    sections:
      - standard # Standard section: captures all standard packages.
      - default # Default section: contains all imports that could not be matched to another section type.
      - prefix(gitlab.online-fx.com) # Custom section: groups all imports with the specified Prefix.
      - prefix(github.com) # Custom section: groups all imports with the specified Prefix.
      - prefix(gorm.io) # Custom section: groups all imports with the specified Prefix.
      - blank # Blank section: contains all blank imports. This section is not present unless explicitly enabled.
      - dot # Dot section: contains all dot imports. This section is not present unless explicitly enabled.

  gocognit:
    min-complexity: 100

  goconst:
    min-occurrences: 10

  gocyclo:
    min-complexity: 50

  gocritic:
    enabled-checks:
      - nestingReduce
      - unnamedResult
      - ruleguard
      - truncateCmp

  gofumpt:
    module-path: app  # Имя модуля которое прописано в go.mod
    extra-rules: true

  gosec:
    excludes:
      - "G107"
      - "G114"
      - "G601"

  lll:
    line-length: 140

  nestif:
    min-complexity: 50

  revive:
    rules:
      - name: var-naming
        disabled: true

  stylecheck:
    checks: [ "all", "-ST1003" ]
    # "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022"

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
    # - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - exportloopref
    - funlen
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    # - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagliatelle
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
